// Test-only Library fixtures — Core-shaped rows for exercising the pure helpers
// in libraryItems.ts. Not imported by app code (the live Library reads from Core
// via useLibraryItems); only *.test.ts files consume this. One coherent personal
// workspace mirroring CONTEXT.md's vocabulary, so the assertions read naturally.

import type { Person, Project, Todo } from "@/lib/libraryItems";

export const people: Person[] = [
	{
		id: "person_priya",
		kind: "person",
		name: "Priya Nair",
		note: "Owns the SDK examples. Flagged the dual-write rewrite risk on the contacts rename; prefers the /v2 alias path.",
		createdAt: "Today, 10:42",
		recency: 95,
	},
	{
		id: "person_alice",
		kind: "person",
		name: "Alice Whitman",
		aliases: ["Allie"],
		note: "Handling the daycare transition. Needs the updated schedule by Friday.",
		createdAt: "Today, 09:12",
		recency: 90,
	},
	{
		id: "person_marco",
		kind: "person",
		name: "Marco Reyes",
		note: "Quoted the garden retaining wall. Waiting on the revised estimate after the drainage change.",
		createdAt: "Yesterday",
		recency: 70,
	},
	{
		id: "person_dana",
		kind: "person",
		name: "Dana Osei",
		note: "Reviewing the Inkstone library surface. Likes the restrained pink direction; wants the empty states to teach.",
		createdAt: "May 28",
		recency: 50,
	},
	{
		id: "person_sam",
		kind: "person",
		name: "Sam Brennan",
		note: "Coming for dinner Saturday. Vegetarian, no mushrooms.",
		createdAt: "May 26",
		recency: 40,
	},
	{
		id: "person_lena",
		kind: "person",
		name: "Dr. Lena Fischer",
		note: "Six-month cleaning overdue. Office prefers Tuesday mornings.",
		createdAt: "May 20",
		recency: 30,
	},
];

export const projects: Project[] = [
	{
		id: "proj_apiv2",
		kind: "project",
		name: "API v2 migration",
		status: "active",
		outcome:
			"Rename /contacts → /v2/contacts behind a 90-day alias. Cutover the weekend after the backfill completes.",
		// Review overdue (before today 2026-06-12) — surfaces in the Review view.
		nextReviewAt: "2026-06-07T20:00:00",
		lastReviewedAt: "2026-05-31T20:00:00",
		createdAt: "Today, 10:42",
		recency: 92,
	},
	{
		id: "proj_inkstone",
		kind: "project",
		name: "Inkstone",
		status: "active",
		outcome:
			"Local-first thinking surface. Currently building the Library: a home for the knowledge chat accrues.",
		// Review in the future — not yet due.
		nextReviewAt: "2026-06-21T20:00:00",
		createdAt: "May 28",
		recency: 55,
	},
	{
		id: "proj_garden",
		kind: "project",
		name: "Garden rebuild",
		status: "on_hold",
		outcome:
			"Retaining wall plus a raised bed. On hold until Marco's revised estimate with the new drainage lands.",
		// On-hold and review overdue — surfaces in the Review view too.
		nextReviewAt: "2026-06-08T20:00:00",
		createdAt: "Yesterday",
		recency: 68,
	},
	{
		id: "proj_lisbon",
		kind: "project",
		name: "Lisbon trip",
		status: "active",
		outcome:
			"Five days in late June. Flights to book this week; loose plan to base in Alfama.",
		nextReviewAt: "2026-06-21T20:00:00",
		createdAt: "May 24",
		recency: 38,
	},
];

export const todos: Todo[] = [
	{
		id: "todo_backfill",
		personRefs: [],
		kind: "todo",
		title: "Backfill /v2/contacts before the cutover window",
		status: "active",
		dueAt: "2026-06-12T17:00:00",
		projectId: "proj_apiv2",
		note: "~2.3M rows. Blocks the weekend cutover.",
		createdAt: "Today, 10:42",
		recency: 94,
	},
	{
		id: "todo_schedule_alice",
		personRefs: [{ personId: "person_alice", role: "related" }],
		kind: "todo",
		title: "Send Alice the updated daycare schedule",
		status: "active",
		dueAt: "2026-06-14T17:00:00",
		createdAt: "Today, 09:12",
		recency: 89,
	},
	{
		id: "todo_sdk",
		personRefs: [{ personId: "person_priya", role: "related" }],
		kind: "todo",
		title: "Update SDK examples (ts, py, go, rb) to /v2/contacts",
		status: "active",
		dueAt: "2026-06-17T17:00:00",
		projectId: "proj_apiv2",
		createdAt: "Today, 10:42",
		recency: 88,
	},
	{
		id: "todo_dentist",
		personRefs: [],
		kind: "todo",
		title: "Book the overdue dental cleaning",
		status: "active",
		dueAt: "2026-06-11T09:00:00",
		createdAt: "May 20",
		recency: 31,
		note: "Tuesday mornings preferred.",
	},
	{
		id: "todo_flights",
		personRefs: [],
		kind: "todo",
		title: "Book Lisbon flights",
		status: "active",
		dueAt: "2026-06-13T17:00:00",
		projectId: "proj_lisbon",
		createdAt: "May 24",
		recency: 37,
	},
	{
		id: "todo_estimate",
		personRefs: [{ personId: "person_marco", role: "waiting_on" }],
		kind: "todo",
		title: "Chase Marco for the revised wall estimate",
		status: "active",
		dueAt: "2026-06-19T17:00:00",
		projectId: "proj_garden",
		createdAt: "Yesterday",
		recency: 66,
	},
	{
		id: "todo_library",
		personRefs: [{ personId: "person_dana", role: "related" }],
		kind: "todo",
		title: "Ship the Library surface",
		status: "active",
		projectId: "proj_inkstone",
		createdAt: "May 28",
		recency: 54,
	},
	{
		id: "todo_groceries",
		personRefs: [],
		kind: "todo",
		title: "Groceries for Saturday dinner",
		status: "active",
		dueAt: "2026-06-15T17:00:00",
		createdAt: "May 26",
		recency: 41,
		note: "Sam is vegetarian, no mushrooms.",
	},
	{
		id: "todo_cutover",
		personRefs: [],
		kind: "todo",
		title: "Schedule the cutover window with on-call",
		status: "completed",
		completedAt: "2026-06-12T11:00:00",
		projectId: "proj_apiv2",
		createdAt: "Today, 10:43",
		recency: 86,
	},
	{
		id: "todo_empty_states",
		personRefs: [],
		kind: "todo",
		title: "Design the Library empty + first-run states",
		status: "completed",
		completedAt: "2026-05-29T12:00:00",
		projectId: "proj_inkstone",
		createdAt: "May 28",
		recency: 52,
	},
	{
		id: "todo_passport",
		personRefs: [],
		kind: "todo",
		title: "Check passport expiry for Lisbon",
		status: "completed",
		completedAt: "2026-05-25T12:00:00",
		projectId: "proj_lisbon",
		createdAt: "May 24",
		recency: 36,
	},
	{
		id: "todo_old_vendor",
		personRefs: [],
		kind: "todo",
		title: "Evaluate the old payments vendor",
		status: "dropped",
		droppedAt: "2026-05-20T12:00:00",
		note: "Superseded — staying on the current provider.",
		createdAt: "May 18",
		recency: 24,
	},
	{
		id: "todo_buy_milk",
		kind: "todo",
		title: "Buy milk",
		status: "active",
		personRefs: [],
		createdAt: "Today, 08:00",
		recency: 80,
	},
	{
		id: "todo_read_handbook",
		kind: "todo",
		title: "Read the new TypeScript handbook",
		status: "active",
		note: "Skim the narrowing chapter first.",
		personRefs: [],
		createdAt: "May 30",
		recency: 44,
	},
];

/** The whole fixture graph in one array (people + projects + todos). */
export const libraryFixtures = [...people, ...projects, ...todos];
