import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { routeTree } from "./routeTree.gen";
import { RuntimeProvider } from "./runtime.tsx";
import "./index.css";

// Mock data never goes stale: prevent refetch loops.
const queryClient = new QueryClient({
	defaultOptions: {
		queries: { staleTime: Number.POSITIVE_INFINITY },
	},
});

// File-based router (ADR-0024). The route tree is generated by
// `@tanstack/router-plugin` from `src/routes/`. Providers stay ABOVE the
// router so route components read QueryClient + Runtime via context.
const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router;
	}
}

const root = document.getElementById("root");

if (!root) {
	throw new Error("Root element #root not found");
}

createRoot(root).render(
	<StrictMode>
		<QueryClientProvider client={queryClient}>
			<RuntimeProvider>
				<RouterProvider router={router} />
			</RuntimeProvider>
		</QueryClientProvider>
	</StrictMode>,
);
