/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as LibraryRouteRouteImport } from './routes/library/route'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as LibraryTimelineRouteImport } from './routes/library/timeline'
import { Route as LibraryMediaRouteImport } from './routes/library/media'
import { Route as LibraryHealthRouteImport } from './routes/library/health'
import { Route as LibraryGtdRouteImport } from './routes/library/gtd'
import { Route as LibraryKindRouteImport } from './routes/library/$kind'
import { Route as ChatArchivedRouteImport } from './routes/_chat/archived'
import { Route as ChatThreadThreadIdRouteImport } from './routes/_chat/thread.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRouteRoute = LibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const LibraryTimelineRoute = LibraryTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryMediaRoute = LibraryMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryHealthRoute = LibraryHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryGtdRoute = LibraryGtdRouteImport.update({
  id: '/gtd',
  path: '/gtd',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const LibraryKindRoute = LibraryKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const ChatArchivedRoute = ChatArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadThreadIdRoute = ChatThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/library': typeof LibraryRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/': typeof ChatIndexRoute
  '/archived': typeof ChatArchivedRoute
  '/library/$kind': typeof LibraryKindRoute
  '/library/gtd': typeof LibraryGtdRoute
  '/library/health': typeof LibraryHealthRoute
  '/library/media': typeof LibraryMediaRoute
  '/library/timeline': typeof LibraryTimelineRoute
  '/settings/models': typeof SettingsModelsRoute
  '/library/': typeof LibraryIndexRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/archived': typeof ChatArchivedRoute
  '/library/$kind': typeof LibraryKindRoute
  '/library/gtd': typeof LibraryGtdRoute
  '/library/health': typeof LibraryHealthRoute
  '/library/media': typeof LibraryMediaRoute
  '/library/timeline': typeof LibraryTimelineRoute
  '/settings/models': typeof SettingsModelsRoute
  '/': typeof ChatIndexRoute
  '/library': typeof LibraryIndexRoute
  '/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/library': typeof LibraryRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/archived': typeof ChatArchivedRoute
  '/library/$kind': typeof LibraryKindRoute
  '/library/gtd': typeof LibraryGtdRoute
  '/library/health': typeof LibraryHealthRoute
  '/library/media': typeof LibraryMediaRoute
  '/library/timeline': typeof LibraryTimelineRoute
  '/settings/models': typeof SettingsModelsRoute
  '/_chat/': typeof ChatIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/_chat/thread/$threadId': typeof ChatThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/library'
    | '/settings'
    | '/'
    | '/archived'
    | '/library/$kind'
    | '/library/gtd'
    | '/library/health'
    | '/library/media'
    | '/library/timeline'
    | '/settings/models'
    | '/library/'
    | '/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/archived'
    | '/library/$kind'
    | '/library/gtd'
    | '/library/health'
    | '/library/media'
    | '/library/timeline'
    | '/settings/models'
    | '/'
    | '/library'
    | '/thread/$threadId'
  id:
    | '__root__'
    | '/library'
    | '/settings'
    | '/_chat'
    | '/_chat/archived'
    | '/library/$kind'
    | '/library/gtd'
    | '/library/health'
    | '/library/media'
    | '/library/timeline'
    | '/settings/models'
    | '/_chat/'
    | '/library/'
    | '/_chat/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRouteRoute: typeof LibraryRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/library/timeline': {
      id: '/library/timeline'
      path: '/timeline'
      fullPath: '/library/timeline'
      preLoaderRoute: typeof LibraryTimelineRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/library/media': {
      id: '/library/media'
      path: '/media'
      fullPath: '/library/media'
      preLoaderRoute: typeof LibraryMediaRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/library/health': {
      id: '/library/health'
      path: '/health'
      fullPath: '/library/health'
      preLoaderRoute: typeof LibraryHealthRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/library/gtd': {
      id: '/library/gtd'
      path: '/gtd'
      fullPath: '/library/gtd'
      preLoaderRoute: typeof LibraryGtdRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/library/$kind': {
      id: '/library/$kind'
      path: '/$kind'
      fullPath: '/library/$kind'
      preLoaderRoute: typeof LibraryKindRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/_chat/archived': {
      id: '/_chat/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ChatArchivedRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/thread/$threadId': {
      id: '/_chat/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ChatThreadThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface LibraryRouteRouteChildren {
  LibraryKindRoute: typeof LibraryKindRoute
  LibraryGtdRoute: typeof LibraryGtdRoute
  LibraryHealthRoute: typeof LibraryHealthRoute
  LibraryMediaRoute: typeof LibraryMediaRoute
  LibraryTimelineRoute: typeof LibraryTimelineRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteRouteChildren: LibraryRouteRouteChildren = {
  LibraryKindRoute: LibraryKindRoute,
  LibraryGtdRoute: LibraryGtdRoute,
  LibraryHealthRoute: LibraryHealthRoute,
  LibraryMediaRoute: LibraryMediaRoute,
  LibraryTimelineRoute: LibraryTimelineRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteRouteWithChildren = LibraryRouteRoute._addFileChildren(
  LibraryRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsModelsRoute: typeof SettingsModelsRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsModelsRoute: SettingsModelsRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ChatRouteChildren {
  ChatArchivedRoute: typeof ChatArchivedRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatThreadThreadIdRoute: typeof ChatThreadThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatArchivedRoute: ChatArchivedRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatThreadThreadIdRoute: ChatThreadThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRouteRoute: LibraryRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
